Repository part4-1st-team/coworkers, pull requests merged in 2024-10, with the labels that each got.

#167 feat: 로그인/회원가입/비밀번호 재설정 페이지 퍼블리싱 #33
  package-lock.json
  package.json
  src/constants/authConstants.ts
  src/containers/auth/signin.tsx
  src/containers/auth/signup.tsx
  src/containers/oauth/google.tsx
  src/containers/oauth/kakao.tsx
  src/libs/axios.ts
  src/libs/refreshAccessToken.ts
  src/stores/userStore.ts
Labels: ✨ feat, 💄 style, ♻️ refactor

#168 fix/#152 상세게시글 수정기능 변경 및 케밥 페이지 이동 수정
  src/components/button/baseButton.tsx
  src/components/button/button.tsx
  src/components/button/floatingButton.tsx
  src/components/input/boxInput.tsx
  src/components/input/editCommentInput.tsx
  src/components/input/replyInput.tsx
  src/containers/board/articleList/articleList.tsx
  src/containers/board/articleList/articleListCard/articleListCard.tsx
  src/containers/board/bestArticleList/bestArticleCard/bestArticleCard.tsx
  src/containers/board/commponent/boardHeader.tsx
  src/containers/board/commponent/floatingActionButton.tsx
  src/containers/board/detailBoard/addComment/addComment.tsx
  src/containers/board/detailBoard/comment/commentcard/commentcard.tsx
  src/containers/board/detailBoard/detailContent/detailContent.tsx
  src/pages/board/index.tsx
  tsconfig.json
Labels: 💄 style, 🐛 fix, ♻️ refactor

#169 feat: 모달 리팩토링 & 자잘한 기능 수정
  src/components/calendar/Calendar.tsx
  src/components/calendar/calendar.css
  src/components/form/FormFieldset.tsx
  src/components/modal/SecessionModal.tsx
  src/components/modal/TaskCreateDateModal.tsx
  src/components/modal/TaskCreateModalWithMemo.tsx
  src/components/modal/TaskEditModal.tsx
  src/components/tooltip/TooltipWrapper.tsx
  src/containers/group/groupId/dropdown/RepeatButton.tsx
  src/containers/group/groupId/tasklist/HalfPage/DoneButton.tsx
  src/containers/group/groupId/tasklist/HalfPage/HalfListContent.tsx
  src/containers/group/groupId/tasklist/Task/Task.tsx
  src/containers/user/AccountSetting/UserSecessionButton.tsx
Labels: ♻️ refactor

#174 feat: 비밀번호 재설정 페이지 기능구현 #33
  src/components/PasswordChangeForm/index.tsx
  src/components/modal/PasswordResetModal.tsx
  src/containers/auth/signin.tsx
  src/containers/auth/signup.tsx
  src/middleware.ts
  src/pages/reset-password/index.tsx
  src/services/userAPI.ts
  tsconfig.json
Labels: ✨ feat, 💄 style, ♻️ refactor

#178 feat/#173 우선순위 기능(즐겨찾기) 구현
  src/assets/images/ic_star_active.png
  src/assets/images/ic_star_empty.png
  src/components/button/enterButton.tsx
  src/components/button/pickerButton.tsx
  src/components/header/UserDropdown.tsx
  src/components/icon/Crown.tsx
  src/components/icon/Email.tsx
  src/components/icon/Google.tsx
  src/components/icon/Kakao.tsx
  src/components/icon/StarActive.tsx
  src/components/icon/StarEmtpy.tsx
  src/components/input/EditInput.tsx
  src/components/input/ReplyInput.tsx
  src/components/modal/TaskCreateDateModal.tsx
  src/containers/auth/signin.tsx
  src/containers/group/groupId/tasklist/DateNavigate.tsx
  src/containers/group/groupId/tasklist/HalfPage/HalfListContent.tsx
  src/containers/group/groupId/tasklist/ListPage.tsx
  src/containers/group/groupId/tasklist/ListPageLayout.tsx
  src/containers/group/groupId/tasklist/ListPriority/PriorityPage.tsx
  src/containers/group/groupId/tasklist/ListPriority/useTaskPriority.ts
  src/containers/group/groupId/tasklist/Task/EmptyTasks.tsx
  src/containers/group/groupId/tasklist/Task/PriorityButton.tsx
  src/containers/group/groupId/tasklist/Task/PriorityTasks.tsx
  src/containers/group/groupId/tasklist/Task/Task.tsx
  src/containers/group/groupId/tasklist/Task/Tasks.tsx
  src/containers/group/groupId/tasklist/Task/TasksSection.tsx
  src/containers/group/groupId/tasklist/TaskList/TaskLists.tsx
  src/containers/group/groupId/tasklist/comment/CommentInput.tsx
  src/containers/group/groupId/tasklist/underline.tsx
  src/containers/group/groupId/useDateStore.ts
  src/containers/user/AccountSetting/AccountSettingForm.tsx
  src/containers/user/AccountSetting/index.tsx
  src/libs/refreshAccessToken.ts
  src/pages/group/[groupId]/tasklist/[taskListId]/index.tsx
  src/pages/group/[groupId]/tasklist/[taskListId]/priority.tsx
  src/services/TaskPriority.API.ts
  src/stores/userStore.ts
  src/types/Icon.d.ts
  src/types/Task.d.ts
Labels: ✨ feat

#190 feat/#186 task 즐겨찾기 아이디별로 뜨게끔 수정
  src/containers/group/groupId/tasklist/DateNavigate.tsx
  src/containers/group/groupId/tasklist/ListPriority/usePriorityMutation.ts
  src/containers/group/groupId/tasklist/ListPriority/useTaskPriority.ts
  src/containers/group/groupId/tasklist/Task/PriorityButton.tsx
  src/containers/group/groupId/tasklist/TaskDoneHandler.ts
  src/containers/group/groupId/useDateStore.ts
  src/services/TaskPriority.API.ts
  src/stores/userStore.ts
  src/types/Task.d.ts
  src/types/User.d.ts
Labels: ♻️ refactor

#194 fix/#193 할일 생성 안 되던 에러 수정
  src/components/button/button.tsx
  src/components/modal/ButtonWrapper.tsx
  src/components/modal/TaskDeleteModal.tsx
  src/components/modal/TaskEditModal.tsx
  src/containers/group/groupId/TaskAddButton.tsx
  src/containers/group/groupId/tasklist/DateNavigate.tsx
  src/containers/group/groupId/tasklist/HalfPage/HalfEditForm.tsx
  src/containers/group/groupId/tasklist/Task/Tasks.tsx
  src/containers/group/groupId/tasklist/Task/TasksSection.tsx
  src/containers/group/groupId/tasklist/TaskListAddPlusButton.tsx
  src/containers/group/groupId/tasklist/TodoAddButton.tsx
Labels: 🐛 fix

#195 refactor/#187 task 코멘트 레이아웃 수정 & task 작성자 구분
  src/containers/group/groupId/tasklist/HalfPage/HalfListContent.tsx
  src/containers/group/groupId/tasklist/Task/Task.tsx
  src/containers/group/groupId/tasklist/comment/Comment.tsx
Labels: ♻️ refactor

#196 style/#188 토스트 컴포넌트 크기 수정 및 모바일/데스크탑 위치 수정
  src/components/toast/Toast.tsx
  src/components/toast/ToastItem.tsx
Labels: 💄 style

#198 style/#197 체크박스 스타일 수정
  public/svgs/ic_check.svg
  src/components/checkbox/Checkbox.tsx
Labels: 💄 style

#200 feat/#199 스켈레톤 애니메이션 & 로딩 스피너
  src/assets/spinner.gif
  src/components/spinner/Spinner.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: ✨ feat

#202 feat#201 404 페이지 제작
  public/svgs/img_todo.svg
  src/pages/404.tsx
Labels: ✨ feat

#204 feat/#203 테마 전환하는 스위치
  public/images/ic_moon.png
  public/images/ic_sun.png
  src/components/switch/ThemeSwitch.css
  src/components/switch/ThemeSwitch.tsx
  src/pages/_app.tsx
Labels: ✨ feat

#206 refactor/#205 그룹 페이지 상세 기능 구현
  src/assets/IconList.tsx
  src/assets/icons/ic_user_export.svg
  src/components/chart/ProgressChart.tsx
  src/components/header/Header.tsx
  src/components/header/UserDropdown.tsx
  src/components/member/MemberInfo.tsx
  src/components/modal/GroupEditModal.tsx
  src/components/modal/GroupMemberRemoveModal.tsx
  src/components/modal/ProfileModal.tsx
  src/components/modal/TaskCreateModal.tsx
  src/components/modal/TaskListEditModal.tsx
  src/components/reportSummary/ReportSummary.tsx
  src/components/sidemenu/SideMenu.tsx
  src/containers/auth/signin.tsx
  src/containers/group/createGroup/CreateGroup.tsx
  src/containers/group/groupId/groupTaskList/GroupBar.tsx
  src/containers/group/groupId/groupTaskList/GroupMembers.tsx
  src/containers/group/groupId/groupTaskList/GroupPage.tsx
  src/containers/group/groupId/groupTaskList/GroupReport.tsx
  src/containers/group/groupId/groupTaskList/GroupTask.tsx
  src/containers/group/groupId/groupTaskList/MemberInviteButton.tsx
  src/containers/group/groupId/groupTaskList/TaskListReport.tsx
  src/containers/group/joinGroup/JoinGroup.tsx
  src/containers/groups/Groups.tsx
  src/mutations/memberDeleteMutation.ts
Labels: ✨ feat, ♻️ refactor

#209 feat: 회원가입 페이지 약관 동의 적용 #185
  src/containers/auth/signin.tsx
  src/containers/auth/signup.tsx
  src/containers/terms/index.tsx
  src/libs/axios.ts
  src/libs/refreshAccessToken.ts
  src/pages/terms/index.tsx
  src/stores/userStore.ts
Labels: ✨ feat

#212 style: 랜딩 페이지 애니메이션 추가
  src/components/modal/GroupLeaveModal.tsx
  src/components/modal/ModalPortal.tsx
  src/containers/landing/componet/ladingMemberContentImage.tsx
  src/containers/landing/componet/landingGroupContentImage.tsx
  src/containers/landing/componet/landingTasklistContentImage.tsx
  src/containers/landing/componet/landingTitle.tsx
  src/containers/landing/landingContentImage/landingContentImage.tsx
  src/containers/landing/landingTitleContent/landingTitleContent.tsx
  src/hooks/useVisibility.ts
  src/pages/index.tsx
Labels: 💄 style

#210 refactor: 카카오 간편 로그인 리팩토링 #208
  next.config.mjs
  src/components/header/UserDropdown.tsx
  src/constants/authConstants.ts
  src/containers/auth/signin.tsx
  src/containers/auth/signup.tsx
  src/containers/oauth/kakao.tsx
Labels: ♻️ refactor

#220 docs: README.md 틀 작성
  README.md
Labels: ✍🏻 docs

#221 docs: README.md 수정
  README.md
Labels: ✍🏻 docs

#222 docs: README.md 수정
  README.md
Labels: ✍🏻 docs

#223 docs: README.md 수정
  README.md
Labels: ✍🏻 docs
