Repository part4-1st-team/coworkers, pull requests merged in 2024-09, with the labels that each got.

#23 feat/#13 modal 컴포넌트 구현
  package-lock.json
  package.json
  src/assets/IconList.tsx
  src/assets/icons/ic_alert.svg
  src/components/modal/CloseWrapper.tsx
  src/components/modal/LogoutModal.tsx
  src/components/modal/MemberDeleteModal.tsx
  src/components/modal/MemberInviteModal.tsx
  src/components/modal/ModalDescription.tsx
  src/components/modal/ModalPortal.tsx
  src/components/modal/ModalTitle.tsx
  src/components/modal/ProfileModal.tsx
  src/components/modal/TaskCreateModal.tsx
  src/components/modal/TaskCreateModalWithMemo.tsx
  src/pages/_document.tsx
  src/stores/ModalStore.ts
  src/styles/globals.css
  src/types/GroupType.d.ts
  tailwind.config.ts
Labels: ✨ feat, 📌 우선순위 : 상

#27 feat/#13 모달 퍼블리싱 완료
  src/components/modal/PasswordChangeModal.tsx
  src/components/modal/PasswordResetModal.tsx
  src/components/modal/TaskCreateDateModal.tsx
Labels: ✨ feat

#39 feat/#14 공통 컴포넌트 구현
  .eslintrc.json
  src/components/button/index.tsx
  src/stories/Button.stories.tsx
  src/styles/globals.css
Labels: ✨ feat

#43 feat: #19 모달에 사용되는 달력 컴포넌트 구현
  package-lock.json
  package.json
  src/components/calendar/Calendar.tsx
  src/components/calendar/calendar.css
  src/pages/_app.tsx
Labels: ✨ feat, ✅ dependency

#44 feat/#41 인풋 공통 컴포넌트 구현
  .prettierrc
  src/components/button/index.tsx
  src/components/input/input.tsx
  src/styles/globals.css
Labels: ✨ feat

#45 feat/#35 마이 히스토리 페이지 퍼블리싱
  src/components/modal/TaskCreateDateModal.tsx
  src/containers/user/myhistory/DailyTaskHistory.tsx
  src/containers/user/myhistory/HistoryList.tsx
  src/containers/user/myhistory/MyHistory.tsx
  src/pages/_app.tsx
  src/pages/user/my-history.tsx
  src/styles/globals.css
  src/types/TaskType.d.ts
Labels: ✨ feat

#47 feat/#38 api 인스턴스 생성
  src/libs/axios.ts
Labels: ✨ feat

#48 feat/#34 list 페이지 퍼블리싱
  src/assets/IconList.tsx
  src/assets/icons/ic_repeat.svg
  src/containers/group/groupId/tasklist/List.tsx
  src/containers/group/groupId/tasklist/TastList.tsx
  src/pages/group/[groupId]/tasklist/[tastlistId].tsx
  src/types/Task.d.ts
  src/utils/getDaily.ts
  src/utils/getDate.ts
Labels: ✨ feat

#50 feat/#36 계정 설정 페이지 퍼블리싱
  src/assets/IconList.tsx
  src/assets/icons/ic_secession.svg
  src/containers/user/AccountSetting/index.tsx
  src/pages/user/account-setting.tsx
  src/stores/ModalStore.ts
Labels: ✨ feat

#51 feat/#38 api axios 함수 정리
  src/containers/group/groupId/tasklist/List.tsx
  src/containers/group/groupId/tasklist/TastList.tsx
  src/containers/user/myhistory/HistoryList.tsx
  src/services/ImageAPI.ts
  src/services/TaskAPI.ts
  src/services/TaskListAPI.ts
  src/services/userAPI.ts
  src/styles/globals.css
  src/types/Image.d.ts
  src/types/Task.d.ts
  src/types/TaskList.d.ts
  src/types/TaskType.d.ts
  src/types/User.d.ts
  src/types/userAPIType.ts
Labels: ✨ feat

#52 feat: 일정 일시 선택 기능 구현 #19
  src/components/calendar/Calendar.tsx
  src/components/timeSelect/TimePicker.tsx
  tailwind.config.ts
Labels: ✨ feat, 💄 style

#53 feat: 추가 버튼 구현 #14
  public/svgs/ic_arrow_btn_left.svg
  public/svgs/ic_arrow_btn_right.svg
  public/svgs/ic_arrow_btn_top_gray.svg
  public/svgs/ic_arrow_btn_top_white.svg
  public/svgs/ic_calendar.svg
  public/svgs/ic_check_gray.svg
  public/svgs/ic_check_green.svg
  public/svgs/ic_check_white.svg
  public/svgs/ic_edit.svg
  public/svgs/ic_plus.svg
  src/components/button/arrowButton.tsx
  src/components/button/button.tsx
  src/components/button/calendarButton.tsx
  src/components/button/editButton.tsx
  src/components/button/enterButton.tsx
  src/components/button/floatingButton.tsx
  src/components/button/pickerButton.tsx
  src/components/button/radioButton.tsx
  src/components/input/input.tsx
  src/styles/globals.css
Labels: ✨ feat

#55 chore/#54 pxr 적용
  package-lock.json
  package.json
  src/styles/globals.css
  tailwind.config.ts
Labels: ✅ dependency

#56 feat: 일정 일시 선택 기능 구현 #19
  package-lock.json
  package.json
  public/svgs/ic_member.svg
  public/svgs/ic_verticalEllipsis.svg
  src/components/memberInfo/MemberInfo.tsx
  src/components/timeSelect/TimePicker.tsx
  src/styles/globals.css
Labels: ✨ feat

#60 feat : 추가 인풋 및 추가 버튼 수정 #41 ✨ feat
  public/svgs/ic_arrow_btn_left.svg
  public/svgs/ic_arrow_btn_right.svg
  public/svgs/ic_arrow_btn_top_gray.svg
  public/svgs/ic_calendar.svg
  public/svgs/ic_check_white.svg
  public/svgs/ic_plus.svg
  src/assets/IconList.tsx
  src/assets/icons/ic_arrow_top.svg
  src/assets/icons/ic_check_gray.svg
  src/assets/icons/ic_check_green.svg
  src/assets/icons/ic_check_white.svg
  src/assets/icons/ic_edit.svg
  src/components/button/CircleButton.tsx
  src/components/button/arrowButton.tsx
  src/components/button/button.tsx
  src/components/button/calendarButton.tsx
  src/components/button/editButton.tsx
  src/components/button/enterButton.tsx
  src/components/button/floatingButton.tsx
  src/components/button/index.tsx
  src/components/button/pickerButton.tsx
  src/components/button/radioButton.tsx
  src/components/calendar/Calendar.tsx
  src/components/input/accountSettingInput.tsx
  src/components/input/authInput.tsx
  src/components/input/boxInput.tsx
  src/components/input/editCommentInput.tsx
  src/components/input/input.tsx
  src/components/input/replyInput.tsx
  src/styles/globals.css
Labels: ✨ feat, ♻️ refactor

#61 feat/#38 group comment article articleComment api 정리
  src/libs/axios.ts
  src/services/ArticleAPI.ts
  src/services/ArticleCommentAPI.ts
  src/services/GroupAPI.ts
  src/services/TaskCommentAPI.ts
  src/services/userAPI.ts
  src/types/Article.d.ts
  src/types/Comment.d.ts
  src/types/Group.d.ts
  src/types/TaskList.d.ts
  src/types/User.d.ts
Labels: ✨ feat

#62 refactor/#13 모달 리팩토링
  src/components/modal/ButtonWrapper.tsx
  src/components/modal/LogoutModal.tsx
  src/components/modal/MemberDeleteModal.tsx
  src/components/modal/MemberInviteModal.tsx
  src/components/modal/Modal.tsx
  src/components/modal/PasswordChangeModal.tsx
  src/components/modal/PasswordResetModal.tsx
  src/components/modal/ProfileModal.tsx
  src/components/modal/TaskCreateDateModal.tsx
  src/components/modal/TaskCreateModal.tsx
  src/components/modal/TaskCreateModalWithMemo.tsx
  src/pages/_app.tsx
  src/stores/ModalStore.ts
  src/styles/globals.css
Labels: ♻️ refactor

#64 feat/#63 history 훅 작성 및 히스토리 페이지 수정
  src/containers/user/myhistory/DailyTaskHistory.tsx
  src/containers/user/myhistory/HistoryList.tsx
  src/containers/user/myhistory/MyHistory.tsx
  src/hooks/useHistory.ts
  src/hooks/useReactQuery.tsx
  src/pages/_app.tsx
  src/styles/globals.css
  src/types/User.d.ts
  src/utils/getSortedHistoryByDate.ts
Labels: ✨ feat

#67 feat/#30 #31 #32 게시판 퍼블리싱 구현
  src/assets/IconList.tsx
  src/assets/icons/ic_heart.svg
  src/assets/icons/ic_medal.svg
  src/assets/icons/ic_member.svg
  src/assets/icons/ic_plus.svg
  src/assets/icons/ic_search.svg
  src/assets/images/img_Mask_group.png
  src/components/button/CircleButton.tsx
  src/components/button/button.tsx
  src/components/button/floatingButton.tsx
  src/components/button/index.tsx
  src/components/input/boxInput.tsx
  src/components/input/input.tsx
  src/components/input/searchInput.tsx
  src/containers/board/articleList/artcivleList.tsx
  src/containers/board/articleList/articleListCard/articleListCard.tsx
  src/containers/board/bestArticleList/bestArticleCard/bestArticleCard.tsx
  src/containers/board/bestArticleList/bestArticleList.tsx
  src/containers/board/detailBoard/comment/commentList.tsx
  src/containers/board/detailBoard/comment/commentcard/commentcard.tsx
  src/containers/board/detailBoard/detailContent/detailContent.tsx
  src/pages/board/[boardId]/index.tsx
  src/pages/board/add-post.tsx
  src/pages/board/index.tsx
  src/styles/globals.css
Labels: ✨ feat

#68 feat/#22 dropdown 컴포넌트 구현
  src/components/dropdown/Dropdown.tsx
  src/components/dropdown/DropdownList.tsx
  src/components/dropdown/DropdownMenu.tsx
  src/components/dropdown/DropdownTrigger.tsx
  src/hooks/useDetectClose.tsx
  src/hooks/useDropdown.ts
  tailwind.config.ts
Labels: ✨ feat

#70 Feature/#14 basebutton refactor
  src/assets/icons/ic_check_gray.svg
  src/components/button/CircleButton.tsx
  src/components/button/arrowButton.tsx
  src/components/button/baseButton.tsx
  src/components/button/calendarButton.tsx
  src/components/button/editButton.tsx
  src/components/button/enterButton.tsx
  src/components/button/floatingButton.tsx
  src/components/button/pickerButton.tsx
  src/components/button/radioButton.tsx
  src/components/input/boxInput.tsx
  src/containers/board/articleList/artticleList.tsx
  src/containers/board/bestArticleList/bestArticleList.tsx
  src/containers/board/detailBoard/detailContent/detailContent.tsx
  src/pages/board/add-post.tsx
  src/pages/board/index.tsx
  src/pages/group/[groupId]/edit.tsx
Labels: ♻️ refactor

#73 feat/#69 list page
  src/assets/IconList.tsx
  src/assets/icons/ic_calendar.svg
  src/assets/icons/ic_pencil.svg
  src/assets/icons/ic_time.svg
  src/components/dropdown/DropdownList.tsx
  src/components/modal/ModalPortal.tsx
  src/components/modal/TaskCreateModal.tsx
  src/containers/group/groupId/tasklist/HalfListContent.tsx
  src/containers/group/groupId/tasklist/HalfPage.tsx
  src/containers/group/groupId/tasklist/HalfPortal.tsx
  src/containers/group/groupId/tasklist/List.tsx
  src/containers/group/groupId/tasklist/Task.tsx
  src/containers/group/groupId/tasklist/Tasks.tsx
  src/containers/group/groupId/tasklist/comment/Comment.tsx
  src/containers/group/groupId/tasklist/comment/CommentInput.tsx
  src/containers/group/groupId/tasklist/comment/KebabDropdown.tsx
  src/hooks/useDropdown.ts
  src/hooks/useEscapeClose.ts
  src/hooks/useTaskLists.ts
  src/hooks/useTasks.ts
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/group/[groupId]/tasklist/[tasklistId].tsx
  src/pages/group/[groupId]/tasklist/[tastlistId].tsx
  src/services/TaskAPI.ts
  src/services/TaskListAPI.ts
  src/stores/HalfPageStore.ts
  src/stores/ModalStore.ts
  src/styles/globals.css
  src/types/Comment.d.ts
  src/types/Group.d.ts
Labels: ✨ feat

#76 feat: 회원가입/로그인 기능 구현 #16
  src/components/input/input.tsx
  src/libs/axios.ts
  src/pages/auth/signin.tsx
  src/services/Auth.API.ts
  src/stores/userStore.ts
  src/styles/globals.css
Labels: ♻️ refactor

#78 feat/#28 group page
  src/assets/IconList.tsx
  src/assets/icons/ic_gear.svg
  src/assets/icons/ic_progress_done.svg
  src/assets/icons/ic_progress_ongoing.svg
  src/assets/images/img_group.png
  src/assets/images/img_mask_group_bar.png
  src/containers/group/groupId/groupTaskList/EmptyGroup.tsx
  src/containers/group/groupId/groupTaskList/GroupBar.tsx
  src/containers/group/groupId/groupTaskList/GroupPage.tsx
  src/containers/group/groupId/groupTaskList/GroupTaskList.tsx
  src/pages/group/[groupId]/edit.tsx
  src/pages/group/[groupId]/index.tsx
Labels: ✨ feat

#80 feat/#74 프로필 수정 버튼 컴포넌트 구현
  public/svgs/ic_modifyProfile.svg
  src/components/profile/modifyProfile.tsx
  src/stories/ModifyProfile.stories.tsx
  tailwind.config.ts
Labels: ✨ feat

#81 feat/#69 list 페이지 기능 구현
  .eslintrc.json
  src/components/button/arrowButton.tsx
  src/components/calendar/Calendar.tsx
  src/components/dropdown/DropdownMenu.tsx
  src/components/dropdown/DropdownTrigger.tsx
  src/components/modal/ModalPortal.tsx
  src/components/modal/TaskCreateDateModal.tsx
  src/components/modal/TaskCreateModal.tsx
  src/components/timeSelect/TimePicker.tsx
  src/containers/group/groupId/dropdown/RepeatButton.tsx
  src/containers/group/groupId/dropdown/RepeatDropdown.tsx
  src/containers/group/groupId/tasklist/HalfListContent.tsx
  src/containers/group/groupId/tasklist/HalfPortal.tsx
  src/containers/group/groupId/tasklist/Task.tsx
  src/containers/group/groupId/tasklist/Tasks.tsx
  src/hooks/useDropdown.ts
  src/hooks/useTaskLists.ts
  src/hooks/useTasks.ts
  src/services/TaskListAPI.ts
  src/types/Task.d.ts
  src/types/TaskList.d.ts
  src/utils/combineDateTime.ts
  src/utils/getDaily.ts
  src/utils/getDate.ts
  src/utils/getMonthDay.ts
  src/utils/getTime.ts
  tailwind.config.ts
Labels: ✨ feat

#84 feat/#19 일정 일시 선택 기능 구현
  src/components/calendar/calendar.css
Labels: 🐛 fix

#86 feat/#69 list page 댓글 기능
  src/components/button/enterButton.tsx
  src/components/button/floatingButton.tsx
  src/components/calendar/Calendar.tsx
  src/components/dropdown/Dropdown.tsx
  src/components/dropdown/DropdownMenu.tsx
  src/components/input/replyInput.tsx
  src/components/modal/TaskCreateDateModal.tsx
  src/containers/group/groupId/TaskAddButton.tsx
  src/containers/group/groupId/tasklist/HalfListContent.tsx
  src/containers/group/groupId/tasklist/Tasks.tsx
  src/containers/group/groupId/tasklist/comment/Comment.tsx
  src/containers/group/groupId/tasklist/comment/CommentInput.tsx
  src/hooks/useTaskCommentList.ts
  src/hooks/useTaskLists.ts
Labels: ✨ feat, 📌 우선순위 : 상

#89 docs: pr 템플릿 수정
  .github/pull_request_template.md
Labels: ✍🏻 docs

#90 feat/#25 토스트 컴포넌트 구현
  src/assets/IconList.tsx
  src/assets/icons/ic_x.svg
  src/assets/icons/ic_x_dark.svg
  src/components/toast/Toast.tsx
  src/components/toast/ToastItem.tsx
  src/components/toast/ToastStore.ts
  src/components/toast/useToast.ts
  src/containers/group/groupId/tasklist/Tasks.tsx
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/stories/Toast.stories.tsx
  src/stories/ToastTest.tsx
  tailwind.config.ts
Labels: ✨ feat

#91 feat/#69 list 페이지 체크리스트, 타임피커 구현
  src/components/calendar/Calendar.tsx
  src/components/calendar/calendar.css
  src/components/modal/TaskCreateDateModal.tsx
  src/containers/group/groupId/tasklist/Task.tsx
  src/containers/group/groupId/tasklist/Tasks.tsx
  src/utils/getDate.ts
  src/utils/getMonthDay.ts
Labels: ✨ feat

#95 feat/#69 list page 기능 구현
  .github/pull_request_template.md
  src/components/button/pickerButton.tsx
  src/components/calendar/Calendar.tsx
  src/components/calendar/calendar.css
  src/components/dropdown/DropdownList.tsx
  src/components/modal/CloseWrapper.tsx
  src/components/modal/TaskCreateDateModal.tsx
  src/containers/group/groupId/EditDeleteDropdown.tsx
  src/containers/group/groupId/TaskAddButton.tsx
  src/containers/group/groupId/tasklist/HalfPage/EditPencilButton.tsx
  src/containers/group/groupId/tasklist/HalfPage/HalfListContent.tsx
  src/containers/group/groupId/tasklist/HalfPage/HalfPage.tsx
  src/containers/group/groupId/tasklist/HalfPage/HalfPortal.tsx
  src/containers/group/groupId/tasklist/Task.tsx
  src/containers/group/groupId/tasklist/Tasks.tsx
  src/containers/group/groupId/tasklist/WeeklyDatePicker.tsx
  src/containers/group/groupId/tasklist/comment/Comment.tsx
  src/containers/group/groupId/tasklist/hooks/useDeleteTaskMutation.ts
  src/containers/group/groupId/tasklist/hooks/useTaskMutation.ts
  src/hooks/useQueryParameter.ts
  src/pages/_app.tsx
  src/services/TaskAPI.ts
  src/types/Task.d.ts
  tailwind.config.ts
Labels: ✨ feat

#96 feat/#28 Group Page
  src/components/member/MemberInfo.tsx
  src/components/modal/ProfileModal.tsx
  src/containers/group/groupId/groupTaskList/GroupBar.tsx
  src/containers/group/groupId/groupTaskList/GroupMembers.tsx
  src/containers/group/groupId/groupTaskList/GroupPage.tsx
  src/containers/group/groupId/groupTaskList/GroupReport.tsx
  src/containers/group/groupId/groupTaskList/GroupTask.tsx
  src/containers/group/groupId/groupTaskList/GroupTaskList.tsx
  src/containers/group/groupId/groupTaskList/MemberInviteButton.tsx
  src/styles/globals.css
  src/types/Mock.ts
Labels: ✨ feat, ♻️ refactor

#98 feat: user store 구현
  src/services/Auth.API.ts
  src/stores/userStore.ts
Labels: ✨ feat

#99 feat/#28 Group Page
  package-lock.json
  package.json
  src/components/chart/DoughnutChart.tsx
  src/containers/group/groupId/groupTaskList/GroupReport.tsx
Labels: ✨ feat, ✅ dependency

#101 fix/#16 signin.tsx 파일 관련 에러 사항 해결 및 파일 이동
  package-lock.json
  package.json
  src/components/input/input.tsx
  src/pages/auth/signin.tsx
  src/pages/auth/signup.tsx
  src/pages/index.tsx
  src/pages/oauth/kakao.tsx
  src/stores/userStore.ts
  src/utils/cookieUtils.ts
Labels: 🐛 fix, ♻️ refactor

#102 feat/#97 계정 설정 페이지 기능 구현
  next.config.mjs
  src/components/input/Label.tsx
  src/components/input/input.tsx
  src/components/member/ProfileImage.tsx
  src/components/member/modifyProfile.tsx
  src/components/modal/MemberDeleteModal.tsx
  src/components/modal/ModalPortal.tsx
  src/components/modal/PasswordChangeModal.tsx
  src/components/profile/modifyProfile.tsx
  src/containers/group/groupId/tasklist/HalfPage/HalfPortal.tsx
  src/containers/user/AccountSetting/ChangePasswordButton.tsx
  src/containers/user/AccountSetting/UserSecessionButton.tsx
  src/containers/user/AccountSetting/index.tsx
  src/hooks/useImageMutation.ts
  src/hooks/useUser.ts
  src/services/ImageAPI.ts
  src/types/userAPIType.ts
Labels: ✨ feat

#104 feat/#24 middleware 구현
  src/libs/axios.ts
  src/libs/refreshAccessToken.ts
  src/middleware.ts
  src/pages/group/groups.tsx
  src/stores/userStore.ts
Labels: ✨ feat

#105 feat/#28 group page
  .env
  src/components/imgUpload/ImgUpload.tsx
  src/containers/group/createGroup/CreateGroup.tsx
  src/containers/group/groupId/groupTaskList/EmptyGroup.tsx
  src/containers/group/groupId/groupTaskList/GroupPage.tsx
  src/containers/group/groupId/groupTaskList/GroupReport.tsx
  src/containers/group/groupId/groupTaskList/GroupTask.tsx
  src/containers/group/groupId/groupTaskList/GroupTaskList.tsx
  src/pages/group/index.tsx
Labels: ✨ feat, ♻️ refactor

#106 feat/#17 헤더 드롭다운 구현
  src/assets/images/img.png
  src/assets/images/img_crown.png
  src/components/dropdown/DropdownMenu.tsx
  src/components/header/Header.tsx
  src/components/header/HeaderGroupDropdown.tsx
  src/components/header/SideTabList.tsx
  src/components/header/UserDropdown.tsx
  src/components/member/ProfileImage.tsx
  src/hooks/useGroups.ts
  src/hooks/useMemberships.tsx
  src/pages/index.tsx
  tailwind.config.ts
Labels: ✨ feat

#108 feat/#107 password change
  src/components/PasswordChangeForm/index.tsx
  src/components/form/errorMessage.tsx
  src/components/input/authInput.tsx
  src/components/input/input.tsx
  src/components/modal/PasswordChangeModal.tsx
  src/constants/validate.ts
  src/containers/user/AccountSetting/index.tsx
  src/containers/user/passwordChange/PasswordChange.tsx
  src/pages/user/password-change.tsx
  src/pages/user/password-reset.tsx
  src/schema/PasswordSchema.ts
  src/styles/globals.css
Labels: ✨ feat

#117 feat: 간편 로그인/회원가입 기능 구현 #92
  src/components/input/input.tsx
  src/pages/auth/signin.tsx
  src/pages/oauth/google.tsx
  src/pages/oauth/kakao.tsx
Labels: ✨ feat

#119 feat/#118 그룹 관련 모달 구현
  src/components/input/input.tsx
  src/components/modal/AlertWrapper.tsx
  src/components/modal/GroupDeleteModal.tsx
  src/components/modal/GroupLeaveModal.tsx
  src/components/modal/GroupMemberRemoveModal.tsx
  src/components/modal/MemberDeleteModal.tsx
  src/components/modal/Modal.tsx
  src/mutations/memberDeleteMutation.ts
Labels: ✨ feat

#123 feat/#69 list 페이지 할 일 수정하기 기능 구현
  src/components/button/floatingButton.tsx
  src/components/checkbox/Checkbox.tsx
  src/containers/group/groupId/tasklist/HalfPage/HalfEditForm.tsx
  src/containers/group/groupId/tasklist/HalfPage/HalfListContent.tsx
  src/containers/group/groupId/tasklist/HalfPage/HalfUserInfo.tsx
  src/containers/group/groupId/tasklist/Task.tsx
  src/containers/group/groupId/tasklist/TaskDoneHandler.ts
  src/containers/group/groupId/tasklist/Tasks.tsx
  src/containers/group/groupId/tasklist/TodoAddButton.tsx
  src/containers/group/groupId/tasklist/hooks/useDeleteTaskMutation.ts
  src/hooks/useTasks.ts
  src/types/Task.d.ts
  tailwind.config.ts
Labels: ✨ feat

#125 feat: 로그인/회원가입/비밀번호 재설정 페이지 퍼블리싱 #33
  src/pages/auth/signin.tsx
Labels: ✨ feat

#128 fix/#65 input 타입 단언 제거
  src/components/input/input.tsx
Labels: 🐛 fix

#127 feat/#126 할 일 수정 모달/할 일 삭제 모달
  src/components/modal/ModalTitle.tsx
  src/components/modal/TaskDeleteModal.tsx
  src/components/modal/TaskEditModal.tsx
  src/containers/group/groupId/tasklist/HalfPage/HalfListContent.tsx
  src/containers/group/groupId/tasklist/Task.tsx
  src/containers/group/groupId/tasklist/Tasks.tsx
  src/containers/group/groupId/tasklist/hooks/useDeleteRecurringMutation.ts
  src/containers/group/groupId/useDayNavigation.ts
  src/middleware.ts
Labels: ✨ feat

#131 refactor/#120 게시글 피드백 적용
  src/components/board/sortDropdown.tsx
  src/components/button/ImageAddButton.tsx
  src/components/button/ImagePreview.tsx
  src/components/button/button.tsx
  src/components/button/floatingButton.tsx
  src/components/button/pickerButton.tsx
  src/components/input/boxInput.tsx
  src/components/input/input.tsx
  src/components/modal/DeleteArticleModal.tsx
  src/containers/board/articleList/articleList.tsx
  src/containers/board/articleList/articleListCard/articleListCard.tsx
  src/containers/board/articleList/artticleList.tsx
  src/containers/board/bestArticleList/bestArticleCard/bestArticleCard.tsx
  src/containers/board/bestArticleList/bestArticleList.tsx
  src/containers/board/detailBoard/comment/addComment/addComment.tsx
  src/containers/board/detailBoard/comment/commentList.tsx
  src/containers/board/detailBoard/comment/commentcard/commentcard.tsx
  src/containers/board/detailBoard/detailContent/detailContent.tsx
  src/hooks/useBestArticles.ts
  src/pages/board/[boardId]/index.tsx
  src/pages/board/add-post.tsx
  src/pages/board/index.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: ✨ feat, 🐛 fix, ♻️ refactor

#130 feat/#28 group page
  src/components/modal/MemberInviteModal.tsx
  src/containers/group/groupId/groupTaskList/GroupMembers.tsx
  src/containers/group/groupId/groupTaskList/GroupPage.tsx
  src/containers/group/groupId/groupTaskList/GroupReport.tsx
  src/containers/group/groupId/groupTaskList/GroupTask.tsx
  src/containers/group/groupId/groupTaskList/MemberInviteButton.tsx
  src/containers/group/joinGroup/JoinGroup.tsx
  src/hooks/useGroups.ts
Labels: ✨ feat, 🐛 fix, ♻️ refactor

#135 feat/#134 리스트 페이지 리팩토링 & UI 개선
  src/assets/IconLeftArrowColor.tsx
  src/assets/icons/ic_arrow_left.svg
  src/components/calendar/Calendar.tsx
  src/containers/group/groupId/tasklist/DateNavigate.tsx
  src/containers/group/groupId/tasklist/ListPage.tsx
  src/containers/group/groupId/tasklist/Task/Task.tsx
  src/containers/group/groupId/tasklist/Task/Tasks.tsx
  src/containers/group/groupId/tasklist/Task/TasksSection.tsx
  src/containers/group/groupId/tasklist/TaskList/TaskList.tsx
  src/containers/group/groupId/tasklist/TaskList/TaskListMenu.tsx
  src/containers/group/groupId/tasklist/TaskList/TaskLists.tsx
  src/containers/group/groupId/tasklist/TaskListAddPlusButton.tsx
  src/containers/group/groupId/tasklist/Tasks.tsx
  src/containers/group/groupId/tasklist/TodoAddButton.tsx
  src/containers/group/groupId/tasklist/underline.tsx
  src/containers/group/groupId/tasklist/useCurrentTaskListName.ts
  src/containers/group/groupId/useDateStore.ts
  src/containers/group/groupId/useDayNavigation.ts
  src/pages/group/[groupId]/tasklist/[tasklistId].tsx
  src/styles/globals.css
  src/utils/getMonthDay.ts
Labels: ✨ feat

#137 feat/#136 group page error
  src/components/header/HeaderGroupDropdown.tsx
  src/containers/group/groupId/groupTaskList/GroupPage.tsx
Labels: 🐛 fix

#138 feat/#26 다크/라이트 모드 기능
  src/hooks/useThemeContext.tsx
  src/pages/_app.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: ✨ feat

#142 feat/#140 tasklist 목록 드래그앤드롭 기능 구현
  src/containers/group/groupId/tasklist/TaskList/TaskList.tsx
  src/containers/group/groupId/tasklist/TaskList/TaskListMenu.tsx
  src/containers/group/groupId/tasklist/TaskList/TaskLists.tsx
  src/hooks/useTaskLists.ts
  src/types/TaskList.d.ts
Labels: ✨ feat

#143 feat/#141 task 일정 리스트 드래그앤드롭 기능 구현
  src/containers/group/groupId/tasklist/Task/Task.tsx
  src/containers/group/groupId/tasklist/Task/Tasks.tsx
  src/containers/group/groupId/tasklist/Task/TasksSection.tsx
  src/hooks/useTasks.ts
  src/services/TaskAPI.ts
  src/types/Task.d.ts
Labels: ✨ feat

#147 feat/#146 task 일정 댓글에 리액션 달기 기능 구현
  src/assets/images/ic_smile.png
  src/containers/group/groupId/tasklist/comment/AddEmoji.tsx
  src/containers/group/groupId/tasklist/comment/Comment.tsx
  src/containers/group/groupId/tasklist/comment/Emoji.tsx
  src/containers/group/groupId/tasklist/comment/useTaskCommentReactionMutation.tsx
  src/hooks/useTaskCommentReaction.tsx
  src/pages/firebaseTest.tsx
  src/services/Reactions.API.ts
  src/types/Reaction.d.ts
Labels: ✨ feat

#148 feat/#28 group page
  src/components/modal/TaskListDeleteModal.tsx
  src/components/modal/TaskListEditModal.tsx
  src/containers/group/groupId/groupTaskList/GroupPage.tsx
  src/containers/group/groupId/groupTaskList/GroupTask.tsx
  src/containers/group/groupId/groupTaskList/GroupTaskList.tsx
Labels: ✨ feat, ♻️ refactor

#149 feat/#145 comment like reply
  src/assets/IconList.tsx
  src/assets/icons/ic_handlike.svg
  src/components/board/ReportDropdownMenu.tsx
  src/containers/board/articleList/articleListCard/articleListCard.tsx
  src/containers/board/bestArticleList/bestArticleCard/bestArticleCard.tsx
  src/containers/board/bestArticleList/bestArticleList.tsx
  src/containers/board/detailBoard/comment/addComment/addComment.tsx
  src/containers/board/detailBoard/comment/commentcard/commentcard.tsx
  src/styles/globals.css
Labels: ✨ feat, ♻️ refactor

#151 style/#150 라이트/다크 모드에 맞춰 컬러 변수 수정
  src/pages/index.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: 💄 style

#158 feat/#157 마이 히스토리 페이지 리팩토링
  package-lock.json
  package.json
  src/components/input/input.tsx
  src/components/modal/HistoryModal.tsx
  src/containers/user/myhistory/DailyTaskHistory.tsx
  src/containers/user/myhistory/History.tsx
  src/containers/user/myhistory/HistoryList.tsx
  src/containers/user/myhistory/MyHistory.tsx
  src/containers/user/myhistory/MyHistoryPage.tsx
  src/containers/user/myhistory/WeekArrowButton.tsx
  src/containers/user/myhistory/WeekHistoryList.tsx
  src/libs/axios.ts
  src/pages/user/my-history.tsx
  src/utils/getSortedHistoryByDate.ts
  src/utils/getSortedHistoryByWeek.ts
  src/utils/getWeekStart.ts
  tailwind.config.ts
Labels: ♻️ refactor

#163 feat/#153 리스트 페이지 리팩토링
  package-lock.json
  package.json
  src/assets/IconLeftArrowColor.tsx
  src/components/dropdown/DropdownList.tsx
  src/components/dropdown/DropdownMenu.tsx
  src/components/header/SideTabList.tsx
  src/components/icon/Crown.tsx
  src/components/member/ProfileImage.tsx
  src/components/modal/ModalDescription.tsx
  src/components/modal/ModalTitle.tsx
  src/components/modal/TaskDeleteModal.tsx
  src/components/tooltip/TooltipWrapper.tsx
  src/containers/group/groupId/tasklist/DateNavigate.tsx
  src/containers/group/groupId/tasklist/HalfPage/HalfEditForm.tsx
  src/containers/group/groupId/tasklist/HalfPage/HalfListContent.tsx
  src/containers/group/groupId/tasklist/HalfPage/HalfPortal.tsx
  src/containers/group/groupId/tasklist/HalfPage/HalfUserInfo.tsx
  src/containers/group/groupId/tasklist/ListPage.tsx
  src/containers/group/groupId/tasklist/Task/Task.tsx
  src/containers/group/groupId/tasklist/Task/Tasks.tsx
  src/containers/group/groupId/tasklist/Task/TasksSection.tsx
  src/containers/group/groupId/tasklist/TaskList/TaskList.tsx
  src/containers/group/groupId/tasklist/TaskList/TaskListMenu.tsx
  src/containers/group/groupId/tasklist/TaskListAddPlusButton.tsx
  src/containers/group/groupId/tasklist/TodoAddButton.tsx
  src/containers/group/groupId/tasklist/comment/AddEmoji.tsx
  src/containers/group/groupId/tasklist/comment/Comment.tsx
  src/containers/group/groupId/tasklist/comment/Emoji.tsx
  src/containers/group/groupId/tasklist/underline.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: ♻️ refactor

#164 feat: cva / tailwind merge를 이용한 클래스 유틸함수 구현
  package-lock.json
  package.json
  src/utils/cn.ts
Labels: ✨ feat
